# Generated by Django 5.1.6 on 2025-02-24 22:37

import django.db.models.deletion
import handbook_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('help_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'действует'), ('deleted', 'удален')], max_length=20)),
                ('img_url', models.CharField(blank=True, max_length=100, null=True)),
                ('', models.CharField(max_length=100)),
                ('', models.FloatField(default=0)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=254, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission', verbose_name='Разрешения')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', handbook_app.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attribute_help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=70, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attribute_helps', to='handbook_app.attribute')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='help_attributes', to='handbook_app.help')),
            ],
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('lesion_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('deleted', 'удален'), ('completed', 'завершен'), ('formed', 'сформирован'), ('rejected', 'отклонен')], max_length=20)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_formation', models.DateTimeField(blank=True, null=True)),
                ('date_of_finish', models.DateTimeField(blank=True, null=True)),
                ('pass_time', models.CharField(blank=True, max_length=30, null=True)),
                ('qr', models.TextField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_lesions', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator_lesions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Help_lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('remaining_quantity', models.CharField(blank=True, max_length=40, null=True)),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Help_lesions', to='handbook_app.help')),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesion_helps', to='handbook_app.lesion')),
            ],
            options={
                'unique_together': {('help', 'lesion')},
            },
        ),
    ]
