# Generated by Django 5.1.6 on 2025-02-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help_lesion',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='help_lesion',
            name='remaining_quantity',
        ),
        migrations.AddField(
            model_name='help_lesion',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
