# Generated by Django 5.1.6 on 2025-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook_app', '0002_remove_help_lesion_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help_lesion',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
