# Generated by Django 5.1.5 on 2025-02-12 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Help",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="URL изображения",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Заголовок")),
                (
                    "description",
                    models.CharField(max_length=520, verbose_name="Описание"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(verbose_name="Длительность (мин)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название поражения"),
                ),
                ("status", models.CharField(max_length=20, verbose_name="Статус")),
                (
                    "date_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "date_applied",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подачи заявки"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="client_lesions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "helper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="helper_lesions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Помощник",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HelpLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.CharField(max_length=249, verbose_name="Комментарий"),
                ),
                (
                    "help",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_lesions",
                        to="main.help",
                        verbose_name="Помощь",
                    ),
                ),
                (
                    "lesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesion_helps",
                        to="main.lesion",
                        verbose_name="Поражение",
                    ),
                ),
            ],
        ),
    ]
