# Generated by Django 5.1.4 on 2025-01-24 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.URLField(verbose_name='URL изображения')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название поражения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('resolved', 'Решено'), ('pending', 'В ожидании')], max_length=20, verbose_name='Статус')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('date_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи заявки')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_lesions', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='helper_lesions', to=settings.AUTH_USER_MODEL, verbose_name='Помощник')),
            ],
        ),
        migrations.CreateModel(
            name='HelpLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True, verbose_name='Продолжительность')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_lesions', to='main.help', verbose_name='Помощь')),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_helps', to='main.lesion', verbose_name='Поражение')),
            ],
        ),
    ]
