# Generated by Django 5.1.3 on 2024-12-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='description',
            field=models.CharField(max_length=520, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='help',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Заголовок'),
        ),
    ]
