# Generated by Django 5.1.5 on 2025-02-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_lesion_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="help",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
